name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install wait-on

      - name: Start client server
        run: npx nx run client:serve > client.log 2>&1 &
      
      - name: Iniciar el servidor en segundo plano
        run: |
          nohup npx nx run server:serve &> server.log &
          sleep 15  # Agrega un pequeño retraso antes de wait-on para dar tiempo al servidor a inicializarse
      
      - name: Esperar a que el servidor esté listo
        run: npx wait-on http://localhost:3000 --timeout 180000 --verbose

      - name: Esperar a que el servidor en localhost:4200 esté listo
        run: npx wait-on http://localhost:4200 --timeout 120000

      - name: Run Cypress tests
        run: |
          npx cypress run --spec "cypress/e2e/**/*.cy.ts" # Ruta a los archivos de prueba de Cypress

      - name: Show client server log
        if: failure()
        run: cat client.log
  
      - name: Show backend server log
        if: failure()
        run: cat server.log


      - name: Archive Cypress videos and screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos-screenshots
          path: |
            cypress/videos
            cypress/screenshots

      - name: Upload Cypress test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results